# Generated by Django 4.0.2 on 2022-06-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='cbtexam.level'),
        ),
    ]
