# Generated by Django 4.0.2 on 2022-06-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0005_alter_quesmodel_ans_alter_quesmodel_op1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherNeed',
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='author_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_subject_class', to='cbtexam.level'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='author_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_subject', to='cbtexam.subject'),
        ),
    ]
