# Generated by Django 4.0.2 on 2022-06-13 21:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0008_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='description2',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
