# Generated by Django 4.0.2 on 2022-06-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0009_scholarships_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='description2',
        ),
    ]
