# Generated by Django 4.0.2 on 2022-06-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0011_scholarshipcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcomments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipcomments', to='cbtexam.scholarships'),
        ),
    ]
