# Generated by Django 4.0.2 on 2022-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0013_ssce_neco_jamb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'verbose_name': 'GCSSE', 'verbose_name_plural': 'GCSSE'},
        ),
        migrations.AddField(
            model_name='subject',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
