# Generated by Django 4.0.2 on 2022-06-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0014_alter_quesmodel_options_subject_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='GCE',
        ),
    ]
