# Generated by Django 4.0.2 on 2022-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0015_rename_quesmodel_gce'),
    ]

    operations = [
        migrations.AddField(
            model_name='gce',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jamb',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='neco',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ssce',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
