# Generated by Django 4.0.2 on 2022-06-17 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0018_alter_level_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCORES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=1000, null=True)),
                ('year', models.CharField(max_length=1000, null=True)),
                ('correct', models.CharField(max_length=200, null=True)),
                ('incorrect', models.CharField(max_length=200, null=True)),
                ('total_score', models.CharField(max_length=200, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectt_teacher', to=settings.AUTH_USER_MODEL)),
                ('author_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectt_class', to='cbtexam.level')),
                ('author_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectt', to='cbtexam.subject')),
            ],
        ),
    ]
