# Generated by Django 4.0.2 on 2022-06-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0019_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='author_class',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='author_subject',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='year',
        ),
    ]
