# Generated by Django 4.0.2 on 2022-06-17 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0020_remove_scores_author_remove_scores_author_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='author_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectclass', to='cbtexam.level'),
        ),
        migrations.AddField(
            model_name='scores',
            name='author_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='cbtexam.subject'),
        ),
        migrations.AddField(
            model_name='scores',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentusername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scores',
            name='year',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
