# Generated by Django 4.0.2 on 2022-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0021_scores_author_class_scores_author_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='year',
        ),
        migrations.AddField(
            model_name='scores',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
