# Generated by Django 4.0.2 on 2022-06-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0022_remove_scores_year_scores_date_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op1score', models.IntegerField()),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op2score', models.IntegerField()),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op3score', models.IntegerField()),
                ('op4', models.CharField(max_length=200, null=True)),
                ('op4score', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
    ]
