# Generated by Django 4.0.2 on 2022-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0023_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='op1score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='op2score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='op3score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='op4score',
            field=models.IntegerField(blank=True),
        ),
    ]
