# Generated by Django 4.0.2 on 2022-07-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtexam', '0025_poll_voter_alter_poll_op1score_alter_poll_op2score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='voter',
        ),
    ]
