from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns =[
    path('password_reset/', views.PasswordReset.as_view(), name ='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name ='password_reset_done'),
    path('confirm_reset/<uidb64>/<token>', views.PasswordResetConfirm.as_view(), name ='password_reset_confirm'),
    path('reset_done/', views.PasswordResetComplete.as_view(), name ='password_reset_complete'),
    path('subject/gce/<pk>/', views.gceexams, name='gceexams'),
    path('subject/jamb/<pk>/', views.jambexams, name='jambexams'),
    path('subject/neco/<pk>/', views.necoexams, name='necoexams'),
    path('subject/ssce/<pk>/', views.ssceexams, name='ssceexams'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(next_page='index'), name= 'login'),
    path('addquestion-gce/', views.QuestionGCE.as_view(), name='addquestiongce'),
    path('addquestion-neco/', views.QuestionNECO.as_view(), name='addquestionneco'),
    path('addquestion-ssce/', views.QuestionSSCE.as_view(), name='addquestionssce'),
    path('addquestion-jamb/', views.QuestionJAMB.as_view(), name='addquestionjamb'),
    path('index/add_question_choice', views.AddQuestion.as_view(), name= 'addquestion'),
    path('logout/', views.CustomLogout.as_view(next_page='index'), name= 'logout'),
    path('schoolnews/', views.Postlist.as_view(), name= 'publist'),
    #path('publications/<slug>/', views.Postdetail.as_view(), name= 'details'),
    path('schoolnews/<slug>/', views.post_detail, name= 'details'),
    path('createpub/', views.PubCreate.as_view(), name= 'createpub'),
    path('delete-pub/<int:pk>', views.DeletePub.as_view(), name ='deletepub'),
    path('update-pub/<int:pk>', views.UpdatePub.as_view(), name ='updatepub'),
    path('scholarships/', views.Scholarshiplist.as_view(), name= 'scholarshiplist'),
    #path('publications/<slug>/', views.Postdetail.as_view(), name= 'details'),
    path('scholarships/<slug>/', views.scholarshipdetail, name= 'scholarshipdetails'),
    path('createscholarship/', views.ScholarshipCreate.as_view(), name= 'createscholarship'),
    path('deletescholarship/<int:pk>', views.DeleteScholarship.as_view(), name ='deletescholarship'),
    path('updatescholarship/<int:pk>', views.UpdateScholarship.as_view(), name ='updatescholarship'),
    path('updatescholarship-newsletter/<int:pk>', views.UpdateScholarshipNewsletter.as_view(), name ='scholarship-nl'),
    path('aboutus/', views.AboutUs.as_view(), name= 'aboutus'),
    path('', views.Index.as_view(), name= 'index'),
    path('subjects-jamb', views.SubjectJAMB.as_view(), name= 'subjectjamb'),
    path('subjects-gce', views.SubjectGCE.as_view(), name= 'subjectgce'),
    path('subjects-neco', views.SubjectNECO.as_view(), name= 'subjectneco'),
    path('subjects-ssce', views.SubjectSSCE.as_view(), name= 'subjectssce'),
    path('index/choose', views.Choose.as_view(), name= 'choose'),
    path('studentprofile/', views.Studentprofile.as_view(), name= 'studentprofile'),
    path('index/premium/', views.Premium.as_view(), name= 'premium'),
    path('createsubjects/', views.CreateSubject.as_view(), name= 'createsubject'),
    #path('update-user/<int:pk>', views.UpdateUser.as_view(), name= 'updateuser'),
    #path('delete-user/<int:pk>', views.UpdateUser.as_view(), name= 'updateuser')
    path('poll/', views.Pollview.as_view(), name= 'polls'),
    path('poll/<int:pk>/', views.polls, name= 'polldetail'),
    ]